### ISSUE TITLE
Is there a way to change the syntax operator for pattern matching so it doesn't conflict with bitwise OR

### ISSUE THREAD

**Issue by CMCDragonkai** [xxllexx/babel-plugin-pattern-matching#1]
Question in the title.

**Comment by CMCDragonkai** [comment]
For example the partial application babel plugin allows rebinding the partial placeholder to another character than `_` (for example to `__`).

**Comment by xxllexx** [comment]
@CMCDragonkai
First you can disable plugin for some places with comment line //@disable-match
and what i can do is to add custom_operator_option to plugin setting

What you think ?

**Comment by CMCDragonkai** [comment]
Yep that's a good idea.

**Comment by xxllexx** [comment]
@CMCDragonkai 
i did invistigation, so the conclusion, babel parser don't allow me to use any other characters, that's why i did this plugin with bitwise OR and bitwise AND

if you know how to do this, i will appreciate for information
Thx

**Comment by CMCDragonkai** [comment]
There's a partial application babel plugin that allows you to change the
character used for the placeholder of the parameter. Perhaps that can be
used?

On 10 Jul 2017 23:16, "Alex Kovalenko" <notifications@github.com> wrote:

@CMCDragonkai <https://github.com/cmcdragonkai>
i did invistigation, so the conclusion, babel parser don't allow me to use
any other characters, that's why i did this plugin with bitwise OR and
bitwise AND

if you know how to do this, i will appreciate for information
Thx

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xxllexx/babel-plugin-pattern-matching/issues/1#issuecomment-314101956>,
or mute the thread

**Comment by xxllexx** [comment]
The parameter for function is easy to handle and change. 
haskell use underscore in pattern matching for argument skipping 
`
    vector :: (x , y) -> b
    vector (_, y) = y
`
So if you want to use underscore in the same way, this is not a problem, this i can add.
But to use underscore like delimiter for patterns, like this: 
`
    let factorial = 0 _ 1;
         factorial = n _ n * factorial(n - 1);
`
Unfortunately, impossible (as i understood), the delimiter should use some of known operators. And i decided to use bitwise, coz it is not used frequently.

**Comment by CMCDragonkai** [comment]
Are you saying that the pattern matching operator must use an operator 
from an existing set of well known javascript operators? You can't just 
allow things like `||`, it needs to be like `+/-/=/&/*/!`...etc?

**Comment by xxllexx** [comment]
Exactly, but `||` is ok. This is logical OR, the one problem with `||` that this is commonly used operator. So the option for this delimiter is to add some leading comment eg: '@pattern' or to declare function name 'match' and inside it will know that logical OR should work differently. 
the snippet with unknown operator: 
[https://astexplorer.net/#/gist/9dd67f5510e4b538a338a864bff12b30/3add5893db3e6c38a73d94156fae9dccd7a15a74](url)

With `||`:
[https://astexplorer.net/#/gist/58ecf1c47ba5d4d242473b6cd94fe187/ffc2d3313000ce60413d85e1810eabf4cf79da2b](url)

With match function: 
[https://astexplorer.net/#/gist/58ecf1c47ba5d4d242473b6cd94fe187/332eb2fb366ff6b211a5010d422a2142bf623b6e](url)

Let me know if you want me to implement all this ways =]

**Comment by xxllexx** [comment]
@CMCDragonkai 
Hi can i close this issue ?

**Comment by CMCDragonkai** [comment]
Hi Alex,

This limitation is unfortunate but yes you can close it if you wish.
